title: Consortium for Open Research Data in the Humanities
email: info@cordh.net
description: digital research infrastructures for the Humanities
baseurl: "/cordh-website" # the subpath of your site, e.g. /blog
url: "https://www.cordh.net" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: xxx
twitter_username: cordhum
linkedin_username: xxx

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  
permalink: /:title/
future: true

# Links
links:
  - title: Partners
    url: '#partners'
  - title: News
    url: /news/
  - title: Contact
    url: '#contact'

footer_links:
  - title: Website Terms & Conditions
    url: '/toc/'
  - title: Privacy & Cookie Policy
    url: /privacy/
  - title: Imprint
    url: /imprint/

# Sass
sass:
  sass_dir: _scss
  style: :compressed

# News
blog:
  hero_layout                : true # turn on hero layout for blog and posts
  hero_placeholder           : "assets/images/generic_hero.jpg" # placeholder for hero image
  excerpts                   : true # show excerpts instead of full post content on blog page
  inline_footnotes           : true # enable/disable barefoot inline footnotes
  titles_only                : false # show post titles only on main blog page

# Pagination
# Pagination
paginate: 4
paginate_path: '/news/page-:num/'
